import Head from "next/head";
import { useEffect } from "react";
import api from "@/services/api";

export default function Home() {
  useEffect(() => {
    api
      .post("/user/register", {
        name: "Eiske",
        email: "e@e.com",
        password: "kanarazu",
      })
      .then((response) => console.log("response: ", response));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
